#!/bin/bash

echo "🚀 Tic-Tac-Toe Multiplayer Game Deployment Guide"
echo "================================================"
echo ""

echo "This script will guide you through deploying the game to production."
echo "We'll use Render.com for the backend and Vercel for the frontend."
echo ""

echo "📋 Prerequisites:"
echo "  ✅ GitHub account (for code hosting)"
echo "  ✅ Render.com account (free tier available)"
echo "  ✅ Vercel account (free tier available)"
echo ""

echo "🎯 Deployment Steps:"
echo ""

echo "1️⃣ STEP 1: Push to GitHub"
echo "   - Create a GitHub repository"
echo "   - Push this code to your repository:"
echo "     git init"
echo "     git add ."
echo "     git commit -m \"Initial commit - Tic-Tac-Toe game\""
echo "     git branch -M main"
echo "     git remote add origin https://github.com/yourusername/your-repo.git"
echo "     git push -u origin main"
echo ""

echo "2️⃣ STEP 2: Deploy Backend to Render.com"
echo "   A. Go to https://render.com and sign up/login"
echo "   B. Click 'New +' → 'Blueprint'"
echo "   C. Connect your GitHub repository"
echo "   D. Render will detect the render.yaml file and set up:"
echo "      - PostgreSQL database"
echo "      - Nakama game server"
echo "   E. Wait for deployment to complete (5-10 minutes)"
echo "   F. Note down your Nakama server URL (something like https://your-app.onrender.com)"
echo ""

echo "3️⃣ STEP 3: Deploy Frontend to Vercel"
echo "   A. Go to https://vercel.com and sign up/login"
echo "   B. Click 'New Project'"
echo "   C. Import your GitHub repository"
echo "   D. Set the root directory to 'frontend'"
echo "   E. Add environment variables:"
echo "      REACT_APP_NAKAMA_HOST=your-nakama-server.onrender.com"
echo "      REACT_APP_NAKAMA_PORT=443"
echo "      REACT_APP_NAKAMA_USE_SSL=true"
echo "      REACT_APP_NAKAMA_SERVER_KEY=defaultkey"
echo "   F. Deploy and note your frontend URL"
echo ""

echo "4️⃣ STEP 4: Test Your Game!"
echo "   A. Open your Vercel URL in two different browsers/devices"
echo "   B. Enter different usernames"
echo "   C. Click 'Find Match' and start playing!"
echo ""

echo "🔧 Alternative Deployment Options:"
echo ""
echo "Option B: Railway (Simplified)"
echo "  1. Install Railway CLI: npm install -g @railway/cli"
echo "  2. Login: railway login"
echo "  3. Deploy: railway up"
echo "  4. Add PostgreSQL: railway add postgresql"
echo ""
echo "Option C: Manual Docker Deployment"
echo "  1. Use any cloud provider (AWS, GCP, Azure, DigitalOcean)"
echo "  2. Deploy using docker-compose.yml"
echo "  3. Set up SSL certificates and domain"
echo ""

echo "📚 Documentation:"
echo "  - Backend API: https://your-nakama-server.onrender.com:7351 (admin console)"
echo "  - Game Architecture: See README.md"
echo "  - Troubleshooting: Check logs in Render dashboard"
echo ""

echo "🎮 Game Features Included:"
echo "  ✅ Real-time multiplayer gameplay"
echo "  ✅ Server-authoritative game logic"
echo "  ✅ Turn timer (30 seconds per move)"
echo "  ✅ Player statistics and leaderboard"
echo "  ✅ Responsive mobile-friendly UI"
echo "  ✅ Connection status indicators"
echo "  ✅ Spectator support"
echo "  ✅ Anti-cheat measures"
echo ""

echo "🆘 Need Help?"
echo "  - Check the logs in your cloud provider dashboard"
echo "  - Ensure all environment variables are set correctly"
echo "  - Verify database connection in Nakama console"
echo "  - Test API endpoints manually"
echo ""

echo "✨ Your multiplayer Tic-Tac-Toe game is ready for production!"
echo "📱 Share the frontend URL with friends to play together!"